language: node_js
node_js:
  - '0.12'
git:
  submodules: false
cache:
  bundler: true
  directories:
  - node_modules # NPM package
  - test/tokens # SUBMODULES
before_script:
  - git submodule update --init lib/
  - git submodule update --init test/php-langspec/
  - if [ ! -f test/tokens/README.md ]; then git submodule update --init test/tokens/; fi
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1d48355795bf25a8f9a
    on_success: change
    on_failure: always
    on_start: never
script: npm run test
after_success: cat /home/travis/build/glayzzle/php-parser-dev/coverage/lcov.info | /home/travis/build/glayzzle/php-parser-dev/node_modules/coveralls/bin/coveralls.js
